[tox]
requires =
    tox>=4.2
env_list =
    py{313, 312, 311, 310}

[testenv]
deps =
    allianceauth
    coverage
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    coverage run -m django test aa_loa -v 2
    coverage report
    coverage xml
install_command = python -m pip install -U {opts} {packages}
