# Generated by Django 5.2.15 on 2026-07-24 14:45

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveOfAbsence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true if the user returned early.",
                    ),
                ),
                (
                    "notified_return",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true once the welcome back notification is sent.",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="If submitted by a Director, this logs who did it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proxy_loas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "permissions": (
                    ("basic_access", "Can access the LOA module"),
                    (
                        "manage_loa",
                        "Can manage LOAs for other users and view HR dashboard",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="LOAConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional Discord Webhook URL for Director notifications when LOAs are created.",
                        null=True,
                    ),
                ),
                (
                    "loa_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Django Group to assign to users while their LOA is active.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOA Config",
                "verbose_name_plural": "LOA Config",
            },
        ),
    ]
